title: "AI ML Bites"
description: "AI, Machine Learning,Python, Java, Backend Development "

theme: minima

author: "Vallisri Sista"

show_excerpts: true

header_pages:
  - about.md
  - resume.md
  - projects.md
  - blogs.md
  - categories.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - assets
