author:
  name: Vallisri S
title: AI ML Bites
description: "Notes on AI, Machine Learning, Backend Development, Embedded Systems, and Software Engineering"
theme: minima

author:
  name: "Vallisri Sista"


header_pages:
  - about.md
  - archive.md
  - categories.md
  - tags.md

minima:
  date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
include:
  - assets
